// <auto-generated />
using Covauto.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Covauto.Domain.Migrations
{
    [DbContext(typeof(CovautoContext))]
    [Migration("20250425091119_AddBeschikbaarToAuto")]
    partial class AddBeschikbaarToAuto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Covauto.Domain.Entities.Auto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Beschikbaar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilometerStand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Beschikbaar = true,
                            KilometerStand = 0,
                            Naam = "Auto 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
